### ISSUE TITLE
decryption stopped working unexpectedly

### ISSUE THREAD

**Issue by MareoRaft** [harryshipton/simple-encryption#1]
I import the library with:

    const encryptor = require('simple-encryptor')('slidsfgslduyfguasdfygsudayfg')

and then I encrypt using `encryptor.encrypt` and save the result in a file.  My application relaunches, grabs the value from the file, and then decrypts with:

    alert(`found encrypted private key: ${value['private-key']}`)
    value['private-key'] = encryptor.decrypt(value['private-key'])
    alert(`decrypted the private key: ${value['private-key']}`)

The first alert correctly displays the encrypted string.  The second alert displays a blank string.  Any idea what is going on here?  I tried uninstalling and reinstalling the module, but to no avail.

**Comment by harryshipton** [comment]
Hey @MareoRaft! I've not touched this module for a while, but I'll take a look at this issue when I wake up for you—I'm certain it'll be a quick fix :)

**Comment by harryshipton** [comment]
Actually you're probably looking for this module: https://github.com/sehrope/node-simple-encryptor

**Comment by MareoRaft** [comment]
Agg.  So sorry about that and thank you!

**Comment by harryshipton** [comment]
No worries! I hope you manage to sort your issue out 😊
